import { useState } from 'react';
import { Button } from '../ui/Button';
import { X, Check, Pencil } from 'lucide-react';
import { SoulUpdateProposal } from '../../lib/soul/soulUpdater';

interface SoulUpdateModalProps {
  proposal: SoulUpdateProposal;
  onAccept: (content: string) => void;
  onReject: () => void;
  onClose: () => void;
}

export function SoulUpdateModal({ proposal, onAccept, onReject, onClose }: SoulUpdateModalProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [editedContent, setEditedContent] = useState(proposal.proposedContent);

  const handleAccept = () => {
    onAccept(isEditing ? editedContent : proposal.proposedContent);
  };

  return (
    <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50">
      <div className="bg-surface border border-border w-full max-w-4xl max-h-[90vh] flex flex-col">
        <div className="flex items-center justify-between px-6 py-4 border-b border-border">
          <h2 className="text-lg font-semibold text-text-primary">Soul Profile Update Proposal</h2>
          <button
            onClick={onClose}
            className="text-text-muted hover:text-text-primary transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-6 space-y-4">
          <div>
            <h3 className="text-sm font-semibold text-text-muted uppercase tracking-wide mb-2">
              Changes Summary
            </h3>
            <div className="bg-background border border-border p-4">
              <pre className="text-sm text-text-primary whitespace-pre-wrap font-mono">
                {proposal.changesSummary}
              </pre>
            </div>
          </div>

          <div>
            <div className="flex items-center justify-between mb-2">
              <h3 className="text-sm font-semibold text-text-muted uppercase tracking-wide">
                Proposed soul.md
              </h3>
              {!isEditing && (
                <Button
                  onClick={() => setIsEditing(true)}
                  variant="ghost"
                  className="flex items-center gap-2 text-xs"
                >
                  <Pencil className="w-3 h-3" />
                  Edit
                </Button>
              )}
            </div>
            
            {isEditing ? (
              <textarea
                value={editedContent}
                onChange={(e) => setEditedContent(e.target.value)}
                className="w-full h-96 bg-background border border-border p-4 text-sm text-text-primary font-mono resize-none focus:outline-none focus:border-accent"
              />
            ) : (
              <div className="bg-background border border-border p-4 h-96 overflow-y-auto">
                <pre className="text-sm text-text-primary whitespace-pre-wrap font-mono">
                  {proposal.proposedContent}
                </pre>
              </div>
            )}
          </div>

          <div className="text-xs text-text-muted bg-background border border-border p-3">
            <strong>Note:</strong> This proposal was generated by AI based on recent dream sessions. 
            Review carefully before accepting. You can edit the content before saving.
          </div>
        </div>

        <div className="flex items-center justify-end gap-3 px-6 py-4 border-t border-border">
          <Button
            onClick={onReject}
            variant="ghost"
            className="text-text-muted hover:text-text-primary"
          >
            Reject
          </Button>
          {isEditing && (
            <Button
              onClick={() => setIsEditing(false)}
              variant="ghost"
            >
              Cancel Edit
            </Button>
          )}
          <Button
            onClick={handleAccept}
            className="flex items-center gap-2 bg-accent hover:bg-accent/90 text-white"
          >
            <Check className="w-4 h-4" />
            Accept {isEditing && '(Edited)'}
          </Button>
        </div>
      </div>
    </div>
  );
}
